packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  sharp: false
  unrs-resolver: true

minimumReleaseAgeExclude:
  - "@expo/cli@57.0.12"
  - "@expo/router-server@57.0.5"
  - "@expo/ui@57.0.9"
  - expo-constants@57.0.9
  - expo-image@57.0.2
  - expo-linking@57.0.5
  - expo-modules-core@57.0.9
  - expo-router@57.0.10
  - expo@57.0.10
  - prettier@3.9.9
  - '@turbo/darwin-64@2.11.4'
  - '@turbo/darwin-arm64@2.11.4'
  - '@turbo/linux-64@2.11.4'
  - '@turbo/linux-arm64@2.11.4'
  - '@turbo/windows-64@2.11.4'
  - '@turbo/windows-arm64@2.11.4'
  - turbo@2.11.4
